pipeline{
    agent any
    stages{
        stage('SCM Checkout'){
            steps{
                git branch: 'master', url: 'https://github.com/PavanGandham/Ansible-Sample-Application-Deployment.git'
            }
        }
        stage('Ansible Init'){
            steps{
                script{
                def tfHome = tool name: 'Ansible'
                env.PATH = "${tfHome}:${env.PATH}"
                sh 'echo $env.PATH'
                sh 'ansible --version'
                }
            }
        }
        stage('Ansible Deploy'){
            steps{
                sh "ansible-playbook main.yml -i inventories/dev/hosts --user ec2-user --key-file ~/.ssh/id_rsa -e '@configs/dev.yml'"
            }
        }
    }
}